/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_wxy_hellondk_MainActivity */

#ifndef _Included_com_example_wxy_hellondk_MainActivity
#define _Included_com_example_wxy_hellondk_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_wxy_hellondk_MainActivity
 * Method:    encryptBase64
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_example_wxy_hellondk_MainActivity_encryptBase64
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_example_wxy_hellondk_MainActivity
 * Method:    decryptBase64
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_example_wxy_hellondk_MainActivity_decryptBase64
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
